PREFIX : <https://github.com/JohnBarakl/RML-Spotify-MiniProject#>
select ?spotifyTrack where {
    ?artist a :SpotifyArtist ;
    	:artistName "Taylor Swift" .
    ?artist :made ?spotifyTrack .
}
LIMIT 5