PREFIX : <https://github.com/JohnBarakl/RML-Spotify-MiniProject#> 

select ?user ?artist where {
    
	?user a :SpotifyUser;
    	:listeningTimeOfDay :Afternoon;
    	:minutesStreamedPerDay ?minutes ;
        :country :Japan ;
    	:mostPlayedArtist ?artist
    FILTER (?minutes > 200)
}
LIMIT 5